<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../src/Zyggy.Core/Zyggy.Core.csproj" />
    <ProjectReference Include="../../src/Zyggy.Node/Zyggy.Node.csproj" />
    <ProjectReference Include="../../src/Zyggy.Cli/Zyggy.Cli.csproj" />
    <ProjectReference Include="../../tools/fake-claude/FakeClaude.csproj" />
  </ItemGroup>

</Project>
