<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>zyggy-hub</AssemblyName>
    <RootNamespace>Zyggy.Hub</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Zyggy.Core/Zyggy.Core.csproj" />
  </ItemGroup>

</Project>
